version: '3.7'
services:
  node_api_server:
    container_name: vision-nem-api
    env_file: .env
    build: ./
    ports:
      - "8082:8082"
    networks:
      - nem-app
    depends_on: 
      - mongo
    links:
      - mongo
  mongo:
    container_name: vision-mongo
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    ports:
      - "27018:27017"
    networks:
      - nem-app
networks:
  nem-app:
    driver: bridge
volumes:
  mongodb:
    driver: local
